# Hipertensión
Elaborado por Mel Flores Alvarado

<h2>Contexto
<p><h4>De acuerdo con la Organización Mundial de la Salud, en el mundo viven cerca de 700 millones de adultos entre 30 y 79 años que sufren de hipertensión. 
    La hipertensión es una enfermedad no transmisible con causas  multifactoriales, la cual puede ser controlable con medicamentos y un estilo de vida saludable.
    Sin embargo, es una enfermedad que rara vez presenta síntomas (asintomática), por lo que su detección podría darse después de presentar algunas complicaciones.
    La hipertensión es una de las principales causas de muerte en el mundo y su padecimiento aumenta el riesgo de padecer enfermedades cardiovasculares como infartos, accidentes cerebrovasculares, enfermedad renal crónica, encefalopatías, etc. 
    Es por ello que es importante tanto prevenir su aparición como diagnosticarla a tiempo. 
    El siguiente dataset contiene los datos de 2000 pacientes. La base de datos fue obtenida de la siguiente liga: https://www.kaggle.com/datasets/pavanbodanki/blood-press

<h2>Objetivo
<h4>Determinar cuántos de los pacientes tienen más riesgo de presentar hipertensión

<h2>Factores de riesgo para presentar hipertensión
<h4>Si bien la hipertensión es una enfermedad multifactorial, existen algunos factores de riesgo que incrementan la probabilidad de padecerla, como son:
    <ul>
        <li>Tabaquismo</li>
        <li>Estrés</li>
        <li>Sedentarismo</li>
        <li>Sobrepeso u obesidad</li>
        <li>Alimentación inadecuada</li>
        <li>Alcoholismo</li>
        <li>Dieta alta en sodio</li>
        <li>Niveles altos de hemoglobina en sangre (ya que esto provoca que aumente la viscosidad de la sangre. Los niveles óptimos son: 
            <li>Mujeres	120–150 unidades.</li>
            <li>Hombres	130–160 pts.</li>
        

<h2>Preguntas de interés
<h4>Algunas preguntas que se podrían plantear son:
<ul>
        <li>¿Cuántas personas tienen riesgo hereditario de padecer hipertensión</li>
        <li>¿En qué rango de edad hay más personas con síntomas de hipertensión</li>
        <li>¿Cuántas personas presentaron anomalías en su presión? ¿Cuántos hombres? ¿Cuántas mujeres?</li>
        <li>¿Cuántas personas tienen un índice de masa corporal mayor a 25?¿Cuántos hombres?¿Cuántas mujeres? ¿Cuántos de cada sexo presentaron anomalías en la presión sanguínea?</li>
        <li>¿Cuántos hombres  fuman y beben? ¿Cuántos de ellos presentaron anomalías en su presión sanguínea?</li>
        <li>¿Cuántas mujeres fuman y beben? ¿Cuántas presentaron anomalías en su presión sanguínea?</li>
        <li>¿Cuántos hombres tienen una dieta alta en sodio? ¿Cuántos de ellos presentaron anomalías en su presión sanguínea?</li>
        <li>¿Cuántas mujeres una dieta alta en sodio? ¿Cuántas presentaron anomalías en su presión sanguínea?</li>
        <li>¿Cuántos hombres  son sedentarios (menos de 10,000 pasos al día)? ¿Cuántos de ellos presentaron anomalías en su presión sanguínea?</li>
        <li>¿Cuántos hombres  son sedentarias (menos de 10,000 pasos al día)? ¿Cuántos de ellos presentaron anomalías en su presión sanguínea?</li>
        <li>¿Cuántos hombres  tienen estrés? ¿Cuántos de ellos presentaron anomalías en su presión sanguínea?</li>
        <li>¿Cuántas mujeres y en qué rango de edad tienen estrés? ¿Cuántas presentaron anomalías en su presión sanguínea?</li>

In [8]:
#Importar librerías
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [9]:
df = pd.read_csv("data.csv")

In [10]:
#Verificar si se cargó correctamente
display(df)

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,1,1,11.28,0.90,34,23,1,1.0,0,45961,48071,NaN,2,1,1
1,2,0,9.75,0.23,54,33,1,NaN,0,26106,25333,205.0,3,0,0
2,3,1,10.79,0.91,70,49,0,NaN,0,9995,29465,67.0,2,1,0
3,4,0,11.00,0.43,71,50,0,NaN,0,10635,7439,242.0,1,1,0
4,5,1,14.17,0.83,52,19,0,NaN,0,15619,49644,397.0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,1,10.14,0.02,69,26,1,NaN,1,26118,47568,144.0,3,1,0
1996,1997,1,11.77,1.00,24,45,1,1.0,1,2572,8063,NaN,3,1,1
1997,1998,1,16.91,0.22,18,42,0,NaN,0,14933,24753,NaN,2,1,1
1998,1999,0,11.15,0.72,46,45,1,NaN,1,18157,15275,253.0,3,0,1
1999,2000,1,11.36,0.09,41,45,0,NaN,0,20729,30463,230.0,1,1,0

In [7]:
#Obtener columnas
nombre_columnas=df.columns.values
lista_nombre_columns=list(nombre_columnas)
for x in lista_nombre_columns: #no olvides los :
    print(x)

Patient_Number
Blood_Pressure_Abnormality
Level_of_Hemoglobin
Genetic_Pedigree_Coefficient
Age
BMI
Sex
Pregnancy
Smoking
Physical_activity
salt_content_in_the_diet
alcohol_consumption_per_day
Level_of_Stress
Chronic_kidney_disease
Adrenal_and_thyroid_disorders

<h2>Variables a considerar
    
<h4>Las variables a estudiar son las siguientes:
<ul>
            <li>Genetic_Pedigree_Coefficient= Carga genética (0 a 1; mientras más cercano a 1, mayor la predisposición</li>
            <li>Blood_Pressure_Abnormality= Anomalías en la presión arterial</li>
            <li>Level_of_Hemoglobin= Niveles de hemoglobina</li>
            <li>BMI= índice de masa corporal (normal= 18-24.9, sobrepeso= 25-29.9, obesidad= +30)</li>
            <li>Sex= Género (Hombres=0; Mujeres=1)</li>
            <li>salt_content_in_the_diet= Contenido de sal en la dieta (debe de ser menor a 1000 mg/d)</li>
            <li>alcohol_consumption_per_day= Consumo diario de alcohol (Hombres=300 ml; mujeres=150 ml)</li>
            <li>Smoking= Fuma (No=1; Sí=0)</li>
            <li>Level_of_Stress= Niveles de estrés( 1 = Bajo, 2 = Normal, 3 = Alto)</li>