# Datasets
Elaborado por Mel Flores Alvarado

<h2>PRIMER DATASET: HIPERTENSIÓN
    
<h2>Contexto
<p><h4>De acuerdo con la Organización Mundial de la Salud, en el mundo viven cerca de 700 millones de adultos entre 30 y 79 años que sufren de hipertensión. 
    La hipertensión es una enfermedad no transmisible con causas  multifactoriales, la cual puede ser controlable con medicamentos y un estilo de vida saludable.
    Sin embargo, es una enfermedad que rara vez presenta síntomas (asintomática), por lo que su detección podría darse después de presentar algunas complicaciones.
    La hipertensión es una de las principales causas de muerte en el mundo y su padecimiento aumenta el riesgo de padecer enfermedades cardiovasculares como infartos, accidentes cerebrovasculares, enfermedad renal crónica, encefalopatías, etc. 
    Es por ello que es importante tanto prevenir su aparición como diagnosticarla a tiempo. 
    El siguiente dataset contiene los datos de 2000 pacientes. La base de datos fue obtenida de la siguiente liga: https://www.kaggle.com/datasets/pavanbodanki/blood-press

<h2>Objetivo
<h4>Determinar cuántos de los pacientes tienen más riesgo de presentar hipertensión

<h2>Factores de riesgo para presentar hipertensión
<h4>Si bien la hipertensión es una enfermedad multifactorial, existen algunos factores de riesgo que incrementan la probabilidad de padecerla, como son:
    <ul>
        <li>Tabaquismo</li>
        <li>Estrés</li>
        <li>Sedentarismo</li>
        <li>Sobrepeso u obesidad</li>
        <li>Alimentación inadecuada</li>
        <li>Alcoholismo</li>
        <li>Dieta alta en sodio</li>
        <li>Niveles altos de hemoglobina en sangre (ya que esto provoca que aumente la viscosidad de la sangre. Los niveles óptimos son: 
            <li>Mujeres	120–150 unidades.</li>
            <li>Hombres	130–160 pts.</li>
        

<h2>Preguntas de interés
<h4>Algunas preguntas que se podrían plantear son:
<ul>
        <li>¿Cuántas personas tienen riesgo hereditario de padecer hipertensión</li>
        <li>¿En qué rango de edad hay más personas con síntomas de hipertensión</li>
        <li>¿Cuántas personas presentaron anomalías en su presión? ¿Cuántos hombres? ¿Cuántas mujeres?</li>
        <li>¿Cuántas personas tienen un índice de masa corporal mayor a 25?¿Cuántos hombres?¿Cuántas mujeres? ¿Cuántos de cada sexo presentaron anomalías en la presión sanguínea?</li>
        <li>¿Cuántos hombres  fuman y beben? ¿Cuántos de ellos presentaron anomalías en su presión sanguínea?</li>
        <li>¿Cuántas mujeres fuman y beben? ¿Cuántas presentaron anomalías en su presión sanguínea?</li>
        <li>¿Cuántos hombres tienen una dieta alta en sodio? ¿Cuántos de ellos presentaron anomalías en su presión sanguínea?</li>
        <li>¿Cuántas mujeres una dieta alta en sodio? ¿Cuántas presentaron anomalías en su presión sanguínea?</li>
        <li>¿Cuántos hombres  son sedentarios (menos de 10,000 pasos al día)? ¿Cuántos de ellos presentaron anomalías en su presión sanguínea?</li>
        <li>¿Cuántos hombres  son sedentarias (menos de 10,000 pasos al día)? ¿Cuántos de ellos presentaron anomalías en su presión sanguínea?</li>
        <li>¿Cuántos hombres  tienen estrés? ¿Cuántos de ellos presentaron anomalías en su presión sanguínea?</li>
        <li>¿Cuántas mujeres y en qué rango de edad tienen estrés? ¿Cuántas presentaron anomalías en su presión sanguínea?</li>

In [6]:
#Importar librerías importantes
import pandas as pd
import matplot.pyplot as plt
import numpy as np

In [4]:
dataset1=pd.read_csv("hipertension.csv")

In [5]:
display(dataset1)

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,1,1,11.28,0.90,34,23,1,1.0,0,45961,48071,NaN,2,1,1
1,2,0,9.75,0.23,54,33,1,NaN,0,26106,25333,205.0,3,0,0
2,3,1,10.79,0.91,70,49,0,NaN,0,9995,29465,67.0,2,1,0
3,4,0,11.00,0.43,71,50,0,NaN,0,10635,7439,242.0,1,1,0
4,5,1,14.17,0.83,52,19,0,NaN,0,15619,49644,397.0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,1,10.14,0.02,69,26,1,NaN,1,26118,47568,144.0,3,1,0
1996,1997,1,11.77,1.00,24,45,1,1.0,1,2572,8063,NaN,3,1,1
1997,1998,1,16.91,0.22,18,42,0,NaN,0,14933,24753,NaN,2,1,1
1998,1999,0,11.15,0.72,46,45,1,NaN,1,18157,15275,253.0,3,0,1
1999,2000,1,11.36,0.09,41,45,0,NaN,0,20729,30463,230.0,1,1,0

In [7]:
#Obtener columnas
nombre_columnas=dataset1.columns.values
lista_nombre_columns=list(nombre_columnas)
for x in lista_nombre_columns: #no olvides los :
    print(x)

Patient_Number
Blood_Pressure_Abnormality
Level_of_Hemoglobin
Genetic_Pedigree_Coefficient
Age
BMI
Sex
Pregnancy
Smoking
Physical_activity
salt_content_in_the_diet
alcohol_consumption_per_day
Level_of_Stress
Chronic_kidney_disease
Adrenal_and_thyroid_disorders

<h2>Variables a considerar
    
<h4>Las variables a estudiar son las siguientes:
<ul>
            <li>Genetic_Pedigree_Coefficient= Carga genética (0 a 1; mientras más cercano a 1, mayor la predisposición</li>
            <li>Blood_Pressure_Abnormality= Anomalías en la presión arterial</li>
            <li>Level_of_Hemoglobin= Niveles de hemoglobina</li>
            <li>BMI= índice de masa corporal (normal= 18-24.9, sobrepeso= 25-29.9, obesidad= +30)</li>
            <li>Sex= Género (Hombres=0; Mujeres=1)</li>
            <li>salt_content_in_the_diet= Contenido de sal en la dieta (debe de ser menor a 1000 mg/d)</li>
            <li>alcohol_consumption_per_day= Consumo diario de alcohol (Hombres=300 ml; mujeres=150 ml)</li>
            <li>Smoking= Fuma (No=1; Sí=0)</li>
            <li>Level_of_Stress= Niveles de estrés( 1 = Bajo, 2 = Normal, 3 = Alto)</li>

In [9]:
#Sacar una muestra
dataset1.sample(5)

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
878,879,1,11.39,NaN,39,12,1,1.0,0,11676,19102,349.0,1,1,0
1356,1357,0,13.50,NaN,36,10,0,NaN,1,41156,15944,149.0,1,0,0
205,206,0,11.54,0.80,40,19,1,0.0,0,26837,43375,302.0,3,0,0
137,138,1,14.54,0.95,68,34,1,NaN,1,40321,6220,180.0,2,1,1
1546,1547,0,9.65,0.13,26,31,1,0.0,1,38951,25687,137.0,2,1,0

<h1>SEGUNDO DATASET: HECHOS DE TRÁNSITO

<h2>Contexto
    <h4>Día a día, ocurren accidentes de tránsito en cualquier parte del país. Sin embargo, estos pueden ser más concurrentes al existir un mayor flujo de personas, especialmente en ciudades tan grandes como es la Ciudad de México (de hecho, es la segunda ciudad más poblada a nivel América), donde día a día el tráfico, el estrés, la premura del tiempo y diversos factores provocan que todas las personas que transitan por las calles de esta enorme ciudad estén en riesgo de sufrir un percance.

Es por ello que se eligió la base de datos llamada Hechos_tránsito, la cual compila todos los accidentes registrados en la Ciudad de México desde Enero de 2018 hasta Octubre de 2022.

La base de datos fue obtenida a través de la siguiente liga: https://datos.cdmx.gob.mx/dataset/hechos-de-transito-reportados-por-ssc-base-ampliada-no-comparativa y corresponde a los Datos Abiertos que pone a disposición tanto el gobierno federal como local de México, el cual utiliza el sistema de repositorios de datos abiertos CKAN (https://datos.gob.mx/blog/ckan?category=api-cdn&tag=educacion)

<h2>Objetivo
    <h4>Analizar cuáles son los accidentes de tránsito más comunes y las principales zonas de riesgo en la Ciudad de México

        
<h2>Audiencia
<h4>Si bien es cierto que los accidentes no se pueden prevenir, sí es posible mitigar el riesgo a que ocurran. Así, el presente documento se encargará de analizar algunos datos que podrían ser de interés para los conductores y transeúntes, pues al conocer los lugares donde han ocurrido el mayor número de accidentes, podría ser benéfico para tomar mayores precauciones a la hora de conducir o tomar otras medidas preventivas. 
        Sin embargo, también podría ser de interés para los organismos gubernamentales (como la Subsecretaría de Control de Tránsito), ya que a través del análisis de los hechos ocurridos y del tipo de accidentes, esto podría ser de gran ayuda para  analizar las medidas actuales que se están tomando para prevenir percances automovilísticos, verificar si están funcionando o no, revisar y/o actualizar tanto el reglamento de tránsito como su cumplimiento, y qué otras acciones se podrían tomar, como pudieran ser:
        
<ul>
      <li>Desarrollo y/o actualización de programas y planes que realmente hagan más seguro el tránsito en la metrópoli</li>
      <li>Instalación de nuevos semáforos y verificación del funcionamiento de los semáforos actuales</li>
      <li>Mayor número de elementos de seguridad en los puntos y horas con más accidentes</li>
      <li>Hacer que el reglamento de tránsito sea respetado sin excepciones</li>
      <li>Realizar campañas informativas acerca de los derechos y obligaciones de los automovilistas, motociclistas, ciclistas y transeúntes</li>
    
<h2>Preguntas de interés

<p><h4>Algunas de las preguntas que puede resultar interesante responder son:
<ol>
    <li>¿Cuáles son los hechos de tránsito más comunes en la CDMX?</li>
    <li>¿Qué tipo de vehículo fue el más involucrado? (motocicleta, automóvil, transporte público, etc)
    <li>¿En qué Alcaldías hubo más accidentes registrados?</li>
    <li>¿Hay alguna hora del día donde ocurran más percanes?</li>
    <li>¿En qué meses del año hay más hechos de tránsito?</li>

In [10]:
dataset_2 = pd.read_csv("hechos_transito.csv", sep=",", low_memory=False)

In [11]:
#Verificar que se cargó correctamente
display(dataset_2)

,no_folio,fecha_evento,mes,hora,condicion,tipo_de_evento,coordenada_x,coordenada_y,punto_1,punto_2,...,pasajero_lesionado,motociclista_occiso,motociclista_lesionado,conductor_occiso,conductor_lesionado,diagnostico_occiso,diagnostico_lesionado,origen,rango_de_edades_menores_de_1_ano_occiso,matricula_unidad_medica
0,BJ/200406/03499,06/04/2020,abril,12:50:00,NaN,CHOQUE,19.368116,-99.142903,EJE 7 SUR,ANTILLAS,...,0.0,0.0,0.0,0.0,0.0,NaN,POLICONTUNDIDO,RADIO,NaN,NaN
1,C5/200406/05748,06/04/2020,abril,18:31:00,NaN,CHOQUE,19.301142,-99.115521,CALZ DEL HUESO,RANCHO COLORADO,...,0.0,0.0,1.0,0.0,0.0,NaN,POLICONTUNDIDO,911 CDMX,NaN,NaN
2,C5/200406/05802,06/04/2020,abril,18:39:00,NaN,CHOQUE,19.476843,-99.092207,EJE 5 NTE,AV GRAN CANAL DEL DESAGUE,...,0.0,0.0,1.0,0.0,0.0,NaN,HX BOCA,911 CDMX,NaN,NaN
3,IZ/200406/03058,06/04/2020,abril,11:38:00,NaN,DERRAPADO,19.298474,-98.984670,EJE 10 SUR,AV SAN FCO,...,0.0,0.0,1.0,0.0,0.0,NaN,POLICONTUNDIDO,RADIO,NaN,NaN
4,C5/200406/03762,06/04/2020,abril,13:31:00,NaN,DERRAPADO,19.436170,-99.204754,AV HOMERO,SOFOCLES,...,0.0,0.0,1.0,0.0,0.0,NaN,CX RODILLA IZQ,911 CDMX,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100009,C5/20221031/04295,31/10/2022,octubre,21:01:00,NaN,DERRAPADO,19.388080,-99.075308,EJE 3 SUR,EJE 5 OTE,...,0.0,0.0,1.0,0.0,0.0,NaN,A DESCARTAR FX TERCIO DISTAL EN TIBIA Y PERONE...,LLAMADA DEL 911,0.0,NaN
100010,C5/20221031/04685,31/10/2022,octubre,22:26:00,NaN,DERRAPADO,19.409031,-99.119861,EJE 3 SUR,NICOLAS BRAVO,...,0.0,0.0,1.0,0.0,0.0,NaN,TCE LEVE,RADIO,0.0,NaN
100011,C5/20221031/04892,31/10/2022,octubre,23:17:00,NaN,DERRAPADO,19.400706,-99.137046,CALZ DE TLALPAN,SEGOVIA,...,0.0,0.0,1.0,0.0,0.0,NaN,TCE MODERADO,LLAMADA DEL 911,0.0,NaN
100012,C5/20221031/00739,31/10/2022,octubre,05:22:00,NaN,VOLCADURA,19.385106,-99.186473,EJE 5 SUR,AV REVOLUCION,...,1.0,0.0,0.0,0.0,1.0,NaN,POLICONTUNDIDO POLICONTUNDIDO,LLAMADA DEL 911,0.0,NaN
100013,C5/20221031/00746,31/10/2022,octubre,05:24:00,NaN,VOLCADURA,19.384817,-99.191158,EJE 5 SUR,ANILLO PERIFERICO,...,0.0,0.0,0.0,0.0,1.0,NaN,CX TORAX,LLAMADA DEL 911,0.0,NaN

In [12]:
#Mostrando los 5 primeros valores
dataset_2.head(5)

,no_folio,fecha_evento,mes,hora,condicion,tipo_de_evento,coordenada_x,coordenada_y,punto_1,punto_2,...,pasajero_lesionado,motociclista_occiso,motociclista_lesionado,conductor_occiso,conductor_lesionado,diagnostico_occiso,diagnostico_lesionado,origen,rango_de_edades_menores_de_1_ano_occiso,matricula_unidad_medica
0,BJ/200406/03499,06/04/2020,abril,12:50:00,NaN,CHOQUE,19.368116,-99.142903,EJE 7 SUR,ANTILLAS,...,0.0,0.0,0.0,0.0,0.0,NaN,POLICONTUNDIDO,RADIO,NaN,NaN
1,C5/200406/05748,06/04/2020,abril,18:31:00,NaN,CHOQUE,19.301142,-99.115521,CALZ DEL HUESO,RANCHO COLORADO,...,0.0,0.0,1.0,0.0,0.0,NaN,POLICONTUNDIDO,911 CDMX,NaN,NaN
2,C5/200406/05802,06/04/2020,abril,18:39:00,NaN,CHOQUE,19.476843,-99.092207,EJE 5 NTE,AV GRAN CANAL DEL DESAGUE,...,0.0,0.0,1.0,0.0,0.0,NaN,HX BOCA,911 CDMX,NaN,NaN
3,IZ/200406/03058,06/04/2020,abril,11:38:00,NaN,DERRAPADO,19.298474,-98.984670,EJE 10 SUR,AV SAN FCO,...,0.0,0.0,1.0,0.0,0.0,NaN,POLICONTUNDIDO,RADIO,NaN,NaN
4,C5/200406/03762,06/04/2020,abril,13:31:00,NaN,DERRAPADO,19.436170,-99.204754,AV HOMERO,SOFOCLES,...,0.0,0.0,1.0,0.0,0.0,NaN,CX RODILLA IZQ,911 CDMX,NaN,NaN

In [13]:
#Obteniendo el nombre de las columnas
column_names= dataset_2.columns.values
nombres_columnas_dataset2=list(column_names)
for x in nombres_columnas_dataset2:
    print(x)

no_folio
fecha_evento
mes
hora
condicion
tipo_de_evento
coordenada_x
coordenada_y
punto_1
punto_2
colonia
alcaldia
tipo_de_interseccion
tipo_de_vehiculo_1
tipo_de_vehiculo_2
tipo_de_vehiculo_3
tipo_de_vehiculo_4
marca_de_vehiculo_1
marca_de_vehiculo_2
marca_de_vehiculo_3
marca_de_vehiculo_4
lesiones
edad_occiso
edad_lesionado
se_desconoce_occiso
se_desconoce_lesionado
rango_de_edades_menores_de_1_ano_lesionado
rango_edades_1_4_occiso
rango_edades_1_4_lesionado
rango_edades_5_14_occiso
rango_edades_5_14_lesionado
rango_edades_15_24_occiso
rango_edades_15_24_lesionado
rango_edades_25_34_occiso
rango_edades_25_34_lesionado
rango_edades_35_44_occiso
rango_edades_35_44_lesionado
rango_edades_45_64_occiso
rango_edades_45_64_lesionado
rango_edades_65_occiso
rango_edades_65_lesionado
total_occisos
occisos_femeninos
occisos_masculinos
occiso_se_desconoce
total_lesionados
lesionados_femeninos
lesionados_masculinos
lesionado_se_desconoce
identidad
unidad_medica_de_apoyo
lugar_del_deceso
trasladado_s_lesionado
hospital
dia
hora2
prioridad
observaciones
coordenada
fecha_captura
interseccion_semaforizada
clasificacion_de_la_vialidad
sentido_de_circulacion
zona_vial
cuadrante
sector
reporte
unidad_a_cargo
carpeta_de_investigacion
color_vehiculo_1
color_vehiculo_2
color_vehiculo_3
ruta_de_transporte_publico
peaton_occiso
peaton_lesionado
ciclista_occiso
ciclista_lesionado
pasajero_occiso
pasajero_lesionado
motociclista_occiso
motociclista_lesionado
conductor_occiso
conductor_lesionado
diagnostico_occiso
diagnostico_lesionado
origen
rango_de_edades_menores_de_1_ano_occiso
matricula_unidad_medica

<h2>Variables a considerar

<h4>Las variables más importantes para analizar en este dataset son:
    
<ul>
        <li>Mes</li>
        <li>Hora</li>
        <li>Tipo_de_evento</li>
        <li>Tipo de intersección</li>
        <li>Alcaldía</li>
        <li>Tipo de vehículo 1,2,3 y 4</li>
        <li>Total occisos</li>
        <li>Total lesionados</li>
        <li>peaton_occiso></li>
        <li>peaton_lesionado</li>
        <li>ciclista_occiso</li>
        <li>ciclista_lesionado</li>
        <li>pasajero_occiso</li>
        <li>pasajero_lesionado</li>
        <li>motociclista_occiso</li>
        <li>motociclista_lesionado</li>
        <li>conductor_occiso</li>
        <li>conductor_lesionado</li>

<h1>TERCER DATASET: DELITOS EN LA CDMX

<h2>Contexto
    
<h4>En una ciudad tan poblada como lo es la Ciudad de México, donde habitan casi 10 millones de personas y a donde se desplazan miles de personas de otros estados a trabajar diariamente, no es raro el sufrir algún tipo de percance. Uno de estos percances puede ser el sufrir algún tipo de delito. 
    Es por ello que se decidió analizar todos aquellos delitos que se registraron desde el 01-01-2016 hasta 30-11-2022 en la Ciudad de México de acuerdo con los datos de Fiscalía General de Justicia (FGJ) de la Ciudad de México.
    La base de datos fue obtenida de la siguiente liga: https://datos.cdmx.gob.mx/dataset/carpetas-de-investigacion-fgj-de-la-ciudad-de-mexico 
    
<h2>Objetivo
<h4>El siguiente proyecto tiene como objetivo analizar los principales delitos registrados  en la Ciudad de México
    
<h2>Audiencia
<h4>Cualquier ciudadano que tenga interés de conocer los delitos más comunes que ocurren en la CDMX pero también podría concernir a las autoridades correspondientes a la prevención del delito como la Secretaría de Seguridad Ciudadana y la Secretaría de Gobierno de la Ciudad de México, las cuales se encargan de salvaguardar los derechos de las 16 alcaldías que conforman a la CDMX.

<h2>Datos importantes
    
<h4>Algunos datos que resultan de interés son:
<ul>
    <li>¿En qué año se registraron mayor número de delitos?</li>
    <li>¿Cuáles son los delitos más comunes?</li>
    <li>¿A qué horas se registraron más hechos ocurridos?¿Y a qué hora menos?</li>
    <li>¿En qué meses hubo más delitos registrados?</li>
    <li>¿En qué alcaldía hubo más hechos registrados</li>
    <li>¿Qué colonias han sido las más vulnerables a sufrir un delito?</li>
    <li>¿Qué tipos de delitos son los más comunes? (alto impacto, bajo impacto, etc)</li>

In [14]:
df = pd.read_csv("delitos_2022_cdmx.csv")

In [15]:
#Mostrar que se cargó orrectamente
display(df)

,ao_hechos,mes_hechos,fecha_hechos,hora_hechos,ao_inicio,mes_inicio,fecha_inicio,hora_inicio,delito,fiscalia,agencia,unidad_investigacion,categoria_delito,competencia,alcaldia_hechos,municipio_hechos,colonia_datos,fgj_colonia_registro,longitud,latitud
0,2021.0,Diciembre,31/12/2021,23:00:00,2022,Enero,01/01/2022,00:03:00,ROBO A TRANSEUNTE EN VIA PUBLICA CON VIOLENCIA,FISCALÍA DE INVESTIGACIÓN TERRITORIAL EN ALVAR...,AO-3,UI-1CD,ROBO A TRANSEUNTE EN VÍA PÚBLICA CON Y SIN VIO...,FUERO COMUN,ALVARO OBREGON,NaN,LIBERALES DE 1857,LIBERALES DE 1857,-99.212950,19.394440
1,2021.0,Octubre,29/10/2021,09:00:00,2022,Enero,01/01/2022,00:06:00,ABUSO DE CONFIANZA,AGENCIA DE DENUNCIA DIGITAL,CEN-1,Unidad de Investigación 1 S/D,DELITO DE BAJO IMPACTO,FUERO COMUN,COYOACAN,NaN,SANTA URSULA COAPA (PBLO),PUEBLO DE SANTA URSULA COAPA,-99.142140,19.313110
2,2021.0,Diciembre,31/12/2021,22:30:00,2022,Enero,01/01/2022,00:26:00,LESIONES INTENCIONALES POR ARMA DE FUEGO,FISCALÍA DE INVESTIGACIÓN TERRITORIAL EN GUSTA...,UAT-GAM-3,UI-1SD,LESIONES DOLOSAS POR DISPARO DE ARMA DE FUEGO,FUERO COMUN,VENUSTIANO CARRANZA,NaN,MORELOS I,MORELOS,-99.121390,19.446150
3,2021.0,Diciembre,31/12/2021,23:11:00,2022,Enero,01/01/2022,00:29:00,DAÑO EN PROPIEDAD AJENA CULPOSA POR TRÁNSITO V...,FISCALÍA DE INVESTIGACIÓN TERRITORIAL EN BENIT...,BJ-2,UI-1CD,DELITO DE BAJO IMPACTO,FUERO COMUN,BENITO JUAREZ,NaN,DEL VALLE VII,DEL VALLE CENTRO,-99.174950,19.369630
4,2021.0,Diciembre,31/12/2021,21:30:00,2022,Enero,01/01/2022,00:35:00,VIOLENCIA FAMILIAR,FISCALÍA DE INVESTIGACIÓN TERRITORIAL EN GUSTA...,UAT-GAM-3,UI-1SD,DELITO DE BAJO IMPACTO,FUERO COMUN,GUSTAVO A. MADERO,NaN,LA FORESTAL,FORESTAL,-99.129900,19.559720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221082,2022.0,Noviembre,30/11/2022,21:15:00,2022,Noviembre,30/11/2022,23:47:44,ROBO A NEGOCIO SIN VIOLENCIA POR FARDEROS (TIE...,FISCALÍA DE JUSTICIA PENAL PARA ADOLESCENTES,AEJPA,2 CON DETENIDO,DELITO DE BAJO IMPACTO,FUERO COMUN,COYOACAN,NaN,CTM VI CULHUACAN (U HAB),CULHUACÁN CTM SECCIÓN VII,-99.114511,19.320756
221083,2022.0,Noviembre,30/11/2022,23:00:00,2022,Noviembre,30/11/2022,23:52:26,LESIONES INTENCIONALES POR ARMA BLANCA,FISCALÍA DE INVESTIGACIÓN TERRITORIAL EN VENUS...,VC-3,UI-2CD,DELITO DE BAJO IMPACTO,FUERO COMUN,VENUSTIANO CARRANZA,NaN,NaN,NaN,0.000000,0.000000
221084,2022.0,Noviembre,30/11/2022,12:10:00,2022,Noviembre,30/11/2022,23:55:19,VIOLENCIA FAMILIAR,FISCALÍA DE INVESTIGACIÓN TERRITORIAL EN MIGUE...,UAT-MH-1,UI-1SD,DELITO DE BAJO IMPACTO,FUERO COMUN,AZCAPOTZALCO,NaN,SAN PEDRO XALPA (AMPL) II,AMPLIACIÓN SAN PEDRO XALPA,-99.216191,19.476123
221085,2022.0,Noviembre,15/11/2022,15:00:00,2022,Noviembre,30/11/2022,23:57:00,ROBO DE OBJETOS,FISCALÍA DE INVESTIGACIÓN TERRITORIAL EN COYOACÁN,COY-1,UI-2CD,DELITO DE BAJO IMPACTO,FUERO COMUN,COYOACAN,NaN,AJUSCO II,AJUSCO,-99.159161,19.320731
221086,2022.0,Noviembre,27/11/2022,08:45:00,2022,Noviembre,30/11/2022,23:57:24,FRAUDE,FISCALÍA DE INVESTIGACIÓN TERRITORIAL EN IZTAP...,IZP-9,UI-2SD,DELITO DE BAJO IMPACTO,FUERO COMUN,IZTAPALAPA,NaN,SANTA CRUZ MEYEHUALCO (PBLO),SANTA CRUZ MEYEHUALCO,-99.039338,19.339047

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 221087 entries, 0 to 221086
Data columns (total 20 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ao_hechos             221033 non-null  float64
 1   mes_hechos            221033 non-null  object
 2   fecha_hechos          221033 non-null  object
 3   hora_hechos           221033 non-null  object
 4   ao_inicio             221087 non-null  int64
 5   mes_inicio            221087 non-null  object
 6   fecha_inicio          221087 non-null  object
 7   hora_inicio           221087 non-null  object
 8   delito                221087 non-null  object
 9   fiscalia              221087 non-null  object
 10  agencia               221087 non-null  object
 11  unidad_investigacion  221087 non-null  object
 12  categoria_delito      221087 non-null  object
 13  competencia           221087 non-null  object
 14  alcaldia_hechos       221087 non-null  object
 15  municipio_hechos      2214 non-null    object
 16  colonia_datos         207588 non-null  object
 17  fgj_colonia_registro  208397 non-null  object
 18  longitud              221087 non-null  float64
 19  latitud               221087 non-null  float64
dtypes: float64(3), int64(1), object(16)
memory usage: 33.7+ MB

In [19]:
#Obtenemos nombres de las columnas
columnas=df.columns.values
lista_columnas_df3=list(columnas)
for x in lista_columnas_df3:
    print(x)

ao_hechos
mes_hechos
fecha_hechos
hora_hechos
ao_inicio
mes_inicio
fecha_inicio
hora_inicio
delito
fiscalia
agencia
unidad_investigacion
categoria_delito
competencia
alcaldia_hechos
municipio_hechos
colonia_datos
fgj_colonia_registro
longitud
latitud

<h2>Variables
<h4>Las variables que resultan interesante analizar, porque responden a las preguntas planteadas, son:
<ul>
    <li>Mes</li>
    <li>Fecha_hechos</li>
    <li>Hora_hechos</li>
    <li>Delito</li>
    <li>Categoria_delito</li>
    <li>Alcaldía_hechos</li>
    <li>Colonia_datos</li>